### Spring properties
# Service registers under this name
spring:
  application:
    name: ${nameProject}


<#if eureka>    
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

      
# HTTP Server (Tomcat) Port
server: 
  port: ${port}
</#if>

